import type { ListingWithCommute } from './types';

export const MOCK_DESTINATION = {
  lat: 40.7127,
  lng: -74.0134,
  label: '1 World Trade Center, New York, NY',
};

export const MOCK_LISTINGS: ListingWithCommute[] = [
  {
    id: 'a1b2c3d4-0001-4000-8000-000000000001',
    external_id: 'streeteasy_1001',
    source: 'streeteasy',
    listing_url: 'https://streeteasy.com/rental/1001',
    title: 'Sunny 1BR in Park Slope',
    description:
      'Bright corner unit with exposed brick and hardwood floors throughout. Steps from the F/G trains, Prospect Park, and the best restaurants in Brooklyn.',
    price: 2800,
    price_monthly_cents: 280000,
    bedrooms: 1,
    bathrooms: 1,
    square_feet: 720,
    address_line1: '245 7th Ave',
    address_line2: 'Apt 3C',
    city: 'Brooklyn',
    state: 'NY',
    zip_code: '11215',
    neighborhood: 'Park Slope',
    latitude: 40.6681,
    longitude: -73.9808,
    property_type: 'apartment',
    floor_number: 3,
    year_built: 1928,
    deposit: 2800,
    fee_type: 'no_fee',
    image_urls: [],
    available_date: '2026-07-01',
    pet_policy: { cats_allowed: true, dogs_allowed: true, dog_weight_limit_lbs: 40, pet_deposit_cents: 50000 },
    amenities: ['dishwasher', 'exposed brick', 'hardwood floors', 'laundry in building'],
    has_doorman: false,
    has_elevator: false,
    has_gym: false,
    has_laundry_in_unit: false,
    has_laundry_in_bldg: true,
    has_dishwasher: true,
    has_ac: true,
    pets_allowed: true,
    has_outdoor_space: false,
    is_active: true,
    scraped_at: '2026-06-14T09:00:00Z',
    last_seen_at: '2026-06-14T09:00:00Z',
    commute: {
      commute_mode: 'transit',
      commute_time_seconds: 1740,
      commute_time_display: '29 min',
      distance_meters: 8400,
      num_transfers: 1,
      route_summary: 'F train to Jay St, A train to Fulton St',
      route_steps: [
        {
          step_index: 0,
          mode: 'walking',
          instruction: 'Walk to 9 St / 4 Av Station',
          duration_seconds: 240,
          distance_meters: 310,
        },
        {
          step_index: 1,
          mode: 'transit',
          instruction: 'Take the F train toward Coney Island',
          duration_seconds: 720,
          distance_meters: 5200,
          transit_line: 'F',
          transit_vehicle_type: 'SUBWAY',
          departure_stop: '9 St / 4 Av',
          arrival_stop: 'Jay St - MetroTech',
        },
        {
          step_index: 2,
          mode: 'walking',
          instruction: 'Transfer at Jay St-MetroTech',
          duration_seconds: 180,
          distance_meters: 200,
        },
        {
          step_index: 3,
          mode: 'transit',
          instruction: 'Take the A train toward Far Rockaway',
          duration_seconds: 480,
          distance_meters: 2400,
          transit_line: 'A',
          transit_vehicle_type: 'SUBWAY',
          departure_stop: 'Jay St - MetroTech',
          arrival_stop: 'Fulton St',
        },
        {
          step_index: 4,
          mode: 'walking',
          instruction: 'Walk to 1 World Trade Center',
          duration_seconds: 120,
          distance_meters: 290,
        },
      ],
      peak_time_used: true,
      departure_time_utc: '2026-06-16T12:30:00Z',
      transit_lines: ['F', 'A'],
    },
  },
  {
    id: 'a1b2c3d4-0002-4000-8000-000000000002',
    external_id: 'zillow_2002',
    source: 'zillow',
    listing_url: 'https://zillow.com/homedetails/2002',
    title: 'Modern Studio in Financial District',
    description:
      'High-rise studio with stunning views of the Hudson River. Steps from the 1/2/3 and R/W trains. Full-service building with gym and roof deck.',
    price: 3200,
    price_monthly_cents: 320000,
    bedrooms: 0,
    bathrooms: 1,
    square_feet: 480,
    address_line1: '90 William St',
    city: 'New York',
    state: 'NY',
    zip_code: '10038',
    neighborhood: 'Financial District',
    latitude: 40.7074,
    longitude: -74.0061,
    property_type: 'studio',
    floor_number: 18,
    year_built: 2008,
    deposit: 3200,
    fee_type: 'no_fee',
    image_urls: [],
    available_date: '2026-07-15',
    pet_policy: { cats_allowed: true, dogs_allowed: false },
    amenities: ['gym', 'roof deck', 'doorman', 'elevator', 'dishwasher', 'ac'],
    has_doorman: true,
    has_elevator: true,
    has_gym: true,
    has_laundry_in_unit: true,
    has_laundry_in_bldg: false,
    has_dishwasher: true,
    has_ac: true,
    pets_allowed: true,
    has_outdoor_space: true,
    is_active: true,
    scraped_at: '2026-06-14T09:00:00Z',
    last_seen_at: '2026-06-14T09:00:00Z',
    commute: {
      commute_mode: 'transit',
      commute_time_seconds: 600,
      commute_time_display: '10 min',
      distance_meters: 900,
      num_transfers: 0,
      route_summary: 'Walk to 1 WTC',
      route_steps: [
        {
          step_index: 0,
          mode: 'walking',
          instruction: 'Walk to 1 World Trade Center',
          duration_seconds: 600,
          distance_meters: 900,
        },
      ],
      peak_time_used: true,
      departure_time_utc: '2026-06-16T12:30:00Z',
      transit_lines: [],
    },
  },
  {
    id: 'a1b2c3d4-0003-4000-8000-000000000003',
    external_id: 'apartments_3003',
    source: 'apartments_com',
    listing_url: 'https://apartments.com/3003',
    title: 'Spacious 2BR in Astoria, Queens',
    description:
      'Renovated 2-bedroom apartment with updated kitchen and bath. The N/W trains run express to Manhattan — door to desk in under 40 minutes.',
    price: 2600,
    price_monthly_cents: 260000,
    bedrooms: 2,
    bathrooms: 1,
    square_feet: 950,
    address_line1: '31-12 Ditmars Blvd',
    city: 'Astoria',
    state: 'NY',
    zip_code: '11105',
    neighborhood: 'Astoria',
    latitude: 40.7722,
    longitude: -73.9301,
    property_type: 'apartment',
    floor_number: 2,
    year_built: 1965,
    deposit: 2600,
    fee_type: 'op_fee',
    image_urls: [],
    available_date: '2026-08-01',
    pet_policy: { cats_allowed: true, dogs_allowed: false },
    amenities: ['renovated kitchen', 'dishwasher', 'laundry in building'],
    has_doorman: false,
    has_elevator: false,
    has_gym: false,
    has_laundry_in_unit: false,
    has_laundry_in_bldg: true,
    has_dishwasher: true,
    has_ac: true,
    pets_allowed: true,
    has_outdoor_space: false,
    is_active: true,
    scraped_at: '2026-06-14T09:00:00Z',
    last_seen_at: '2026-06-14T09:00:00Z',
    commute: {
      commute_mode: 'transit',
      commute_time_seconds: 2400,
      commute_time_display: '40 min',
      distance_meters: 12800,
      num_transfers: 0,
      route_summary: 'N train direct to Cortlandt St',
      route_steps: [
        {
          step_index: 0,
          mode: 'walking',
          instruction: 'Walk to Ditmars Blvd Station',
          duration_seconds: 300,
          distance_meters: 380,
        },
        {
          step_index: 1,
          mode: 'transit',
          instruction: 'Take the N train toward Coney Island',
          duration_seconds: 1920,
          distance_meters: 11800,
          transit_line: 'N',
          transit_vehicle_type: 'SUBWAY',
          departure_stop: 'Ditmars Blvd',
          arrival_stop: 'Cortlandt St',
        },
        {
          step_index: 2,
          mode: 'walking',
          instruction: 'Walk to 1 World Trade Center',
          duration_seconds: 180,
          distance_meters: 340,
        },
      ],
      peak_time_used: true,
      departure_time_utc: '2026-06-16T12:30:00Z',
      transit_lines: ['N'],
    },
  },
  {
    id: 'a1b2c3d4-0004-4000-8000-000000000004',
    external_id: 'streeteasy_4004',
    source: 'streeteasy',
    listing_url: 'https://streeteasy.com/rental/4004',
    title: 'Renovated 1BR in Crown Heights',
    description:
      'Gut-renovated one-bedroom in a charming brownstone. Central Crown Heights — A/C trains give you a fast shot into Manhattan.',
    price: 2200,
    price_monthly_cents: 220000,
    bedrooms: 1,
    bathrooms: 1,
    square_feet: 680,
    address_line1: '643 Franklin Ave',
    address_line2: 'Apt 2R',
    city: 'Brooklyn',
    state: 'NY',
    zip_code: '11238',
    neighborhood: 'Crown Heights',
    latitude: 40.6696,
    longitude: -73.9568,
    property_type: 'apartment',
    floor_number: 2,
    year_built: 1910,
    deposit: 4400,
    fee_type: 'no_fee',
    image_urls: [],
    available_date: '2026-07-01',
    pet_policy: { cats_allowed: true, dogs_allowed: true, dog_weight_limit_lbs: 25, pet_monthly_fee_cents: 7500 },
    amenities: ['exposed brick', 'high ceilings', 'dishwasher'],
    has_doorman: false,
    has_elevator: false,
    has_gym: false,
    has_laundry_in_unit: false,
    has_laundry_in_bldg: true,
    has_dishwasher: true,
    has_ac: false,
    pets_allowed: true,
    has_outdoor_space: false,
    is_active: true,
    scraped_at: '2026-06-14T09:00:00Z',
    last_seen_at: '2026-06-14T09:00:00Z',
    commute: {
      commute_mode: 'transit',
      commute_time_seconds: 2700,
      commute_time_display: '45 min',
      distance_meters: 13200,
      num_transfers: 1,
      route_summary: 'A train via Jay St to Fulton St',
      route_steps: [
        {
          step_index: 0,
          mode: 'walking',
          instruction: 'Walk to Franklin Ave Station',
          duration_seconds: 240,
          distance_meters: 280,
        },
        {
          step_index: 1,
          mode: 'transit',
          instruction: 'Take the A train toward Howard Beach',
          duration_seconds: 1920,
          distance_meters: 11400,
          transit_line: 'A',
          transit_vehicle_type: 'SUBWAY',
          departure_stop: 'Franklin Av',
          arrival_stop: 'Jay St - MetroTech',
        },
        {
          step_index: 2,
          mode: 'walking',
          instruction: 'Transfer at Jay St',
          duration_seconds: 180,
          distance_meters: 200,
        },
        {
          step_index: 3,
          mode: 'transit',
          instruction: 'Take the A train one stop',
          duration_seconds: 240,
          distance_meters: 1200,
          transit_line: 'A',
          transit_vehicle_type: 'SUBWAY',
          departure_stop: 'Jay St - MetroTech',
          arrival_stop: 'Fulton St',
        },
        {
          step_index: 4,
          mode: 'walking',
          instruction: 'Walk to 1 World Trade Center',
          duration_seconds: 120,
          distance_meters: 320,
        },
      ],
      peak_time_used: true,
      departure_time_utc: '2026-06-16T12:30:00Z',
      transit_lines: ['A'],
    },
  },
  {
    id: 'a1b2c3d4-0005-4000-8000-000000000005',
    external_id: 'facebook_5005',
    source: 'facebook_marketplace',
    listing_url: 'https://facebook.com/marketplace/item/5005',
    title: 'Private Room in Bushwick Shared Apartment',
    description:
      'Large furnished room in a 3BR apartment. Shared kitchen and living room. L train is a 5-minute walk. Great for young professionals.',
    price: 1800,
    price_monthly_cents: 180000,
    bedrooms: 1,
    bathrooms: 1,
    square_feet: 220,
    address_line1: '52 Wilson Ave',
    city: 'Brooklyn',
    state: 'NY',
    zip_code: '11237',
    neighborhood: 'Bushwick',
    latitude: 40.7037,
    longitude: -73.9188,
    property_type: 'room',
    floor_number: 1,
    deposit: 1800,
    fee_type: 'no_fee',
    image_urls: [],
    available_date: '2026-07-01',
    pet_policy: { cats_allowed: false, dogs_allowed: false },
    amenities: ['furnished', 'wifi included', 'washer/dryer'],
    has_doorman: false,
    has_elevator: false,
    has_gym: false,
    has_laundry_in_unit: true,
    has_laundry_in_bldg: false,
    has_dishwasher: false,
    has_ac: true,
    pets_allowed: false,
    has_outdoor_space: false,
    is_active: true,
    scraped_at: '2026-06-14T09:00:00Z',
    last_seen_at: '2026-06-14T09:00:00Z',
    commute: {
      commute_mode: 'transit',
      commute_time_seconds: 2340,
      commute_time_display: '39 min',
      distance_meters: 10200,
      num_transfers: 1,
      route_summary: 'L train to 8 Av, then walk to WTC',
      route_steps: [
        {
          step_index: 0,
          mode: 'walking',
          instruction: 'Walk to Wilson Av Station',
          duration_seconds: 300,
          distance_meters: 350,
        },
        {
          step_index: 1,
          mode: 'transit',
          instruction: 'Take the L train toward 8 Av',
          duration_seconds: 1320,
          distance_meters: 8200,
          transit_line: 'L',
          transit_vehicle_type: 'SUBWAY',
          departure_stop: 'Wilson Av',
          arrival_stop: '8 Av',
        },
        {
          step_index: 2,
          mode: 'walking',
          instruction: 'Walk to 1 World Trade Center',
          duration_seconds: 720,
          distance_meters: 1650,
        },
      ],
      peak_time_used: true,
      departure_time_utc: '2026-06-16T12:30:00Z',
      transit_lines: ['L'],
    },
  },
  {
    id: 'a1b2c3d4-0006-4000-8000-000000000006',
    external_id: 'streeteasy_6006',
    source: 'streeteasy',
    listing_url: 'https://streeteasy.com/rental/6006',
    title: 'Luxury 2BR/2BA in Battery Park City',
    description:
      'Waterfront luxury building with Hudson River views, concierge, pool, and private park access. Walking distance to 1 WTC.',
    price: 5500,
    price_monthly_cents: 550000,
    bedrooms: 2,
    bathrooms: 2,
    square_feet: 1200,
    address_line1: '200 Rector Pl',
    address_line2: '28F',
    city: 'New York',
    state: 'NY',
    zip_code: '10280',
    neighborhood: 'Battery Park City',
    latitude: 40.7098,
    longitude: -74.0163,
    property_type: 'apartment',
    floor_number: 28,
    year_built: 1996,
    deposit: 11000,
    fee_type: 'broker_fee',
    image_urls: [],
    available_date: '2026-07-01',
    pet_policy: { cats_allowed: true, dogs_allowed: true, dog_weight_limit_lbs: 50, pet_deposit_cents: 100000 },
    amenities: ['pool', 'gym', 'concierge', 'doorman', 'elevator', 'dishwasher', 'washer/dryer in unit', 'ac', 'river views', 'outdoor space'],
    has_doorman: true,
    has_elevator: true,
    has_gym: true,
    has_laundry_in_unit: true,
    has_laundry_in_bldg: false,
    has_dishwasher: true,
    has_ac: true,
    pets_allowed: true,
    has_outdoor_space: true,
    is_active: true,
    scraped_at: '2026-06-14T09:00:00Z',
    last_seen_at: '2026-06-14T09:00:00Z',
    commute: {
      commute_mode: 'transit',
      commute_time_seconds: 900,
      commute_time_display: '15 min',
      distance_meters: 1100,
      num_transfers: 0,
      route_summary: 'Walk to 1 WTC via Vesey St',
      route_steps: [
        {
          step_index: 0,
          mode: 'walking',
          instruction: 'Walk to 1 World Trade Center via Vesey St',
          duration_seconds: 900,
          distance_meters: 1100,
        },
      ],
      peak_time_used: true,
      departure_time_utc: '2026-06-16T12:30:00Z',
      transit_lines: [],
    },
  },
  {
    id: 'a1b2c3d4-0007-4000-8000-000000000007',
    external_id: 'zillow_7007',
    source: 'zillow',
    listing_url: 'https://zillow.com/homedetails/7007',
    title: 'Cozy 1BR in Jackson Heights, Queens',
    description:
      'Comfortable 1-bedroom in the heart of the most diverse neighborhood in the world. E/F/M/R trains offer multiple routes to Manhattan.',
    price: 2100,
    price_monthly_cents: 210000,
    bedrooms: 1,
    bathrooms: 1,
    square_feet: 620,
    address_line1: '75-21 37th Ave',
    city: 'Jackson Heights',
    state: 'NY',
    zip_code: '11372',
    neighborhood: 'Jackson Heights',
    latitude: 40.7488,
    longitude: -73.8900,
    property_type: 'apartment',
    floor_number: 4,
    year_built: 1940,
    deposit: 2100,
    fee_type: 'no_fee',
    image_urls: [],
    available_date: '2026-08-01',
    pet_policy: { cats_allowed: true, dogs_allowed: false },
    amenities: ['laundry in building', 'dishwasher', 'elevator'],
    has_doorman: false,
    has_elevator: true,
    has_gym: false,
    has_laundry_in_unit: false,
    has_laundry_in_bldg: true,
    has_dishwasher: true,
    has_ac: true,
    pets_allowed: true,
    has_outdoor_space: false,
    is_active: true,
    scraped_at: '2026-06-14T09:00:00Z',
    last_seen_at: '2026-06-14T09:00:00Z',
    commute: {
      commute_mode: 'transit',
      commute_time_seconds: 3300,
      commute_time_display: '55 min',
      distance_meters: 16800,
      num_transfers: 1,
      route_summary: 'E train to World Trade Center via 53 St',
      route_steps: [],
      peak_time_used: true,
      departure_time_utc: '2026-06-16T12:30:00Z',
      transit_lines: ['E', 'F'],
    },
  },
  {
    id: 'a1b2c3d4-0008-4000-8000-000000000008',
    external_id: 'apartments_8008',
    source: 'apartments_com',
    listing_url: 'https://apartments.com/8008',
    title: '2BR in Inwood, Manhattan',
    description:
      'Spacious 2BR at the top of Manhattan island. Inwood Hill Park across the street, and the A express train gets you to WTC in under an hour.',
    price: 2400,
    price_monthly_cents: 240000,
    bedrooms: 2,
    bathrooms: 1,
    square_feet: 1050,
    address_line1: '4914 Broadway',
    city: 'New York',
    state: 'NY',
    zip_code: '10034',
    neighborhood: 'Inwood',
    latitude: 40.8677,
    longitude: -73.9218,
    property_type: 'apartment',
    floor_number: 3,
    year_built: 1955,
    deposit: 4800,
    fee_type: 'no_fee',
    image_urls: [],
    available_date: '2026-07-15',
    pet_policy: { cats_allowed: true, dogs_allowed: true, dog_weight_limit_lbs: 60 },
    amenities: ['laundry in building', 'elevator', 'ac'],
    has_doorman: false,
    has_elevator: true,
    has_gym: false,
    has_laundry_in_unit: false,
    has_laundry_in_bldg: true,
    has_dishwasher: false,
    has_ac: true,
    pets_allowed: true,
    has_outdoor_space: false,
    is_active: true,
    scraped_at: '2026-06-14T09:00:00Z',
    last_seen_at: '2026-06-14T09:00:00Z',
    commute_pending: true,
  },
  {
    id: 'a1b2c3d4-0009-4000-8000-000000000009',
    external_id: 'streeteasy_9009',
    source: 'streeteasy',
    listing_url: 'https://streeteasy.com/rental/9009',
    title: 'Loft-style 1BR in Williamsburg',
    description:
      'Open-plan loft with 12-foot ceilings in a converted warehouse. The L train is two blocks away — perfect location for creative professionals.',
    price: 3400,
    price_monthly_cents: 340000,
    bedrooms: 1,
    bathrooms: 1,
    square_feet: 860,
    address_line1: '111 N 7th St',
    address_line2: 'Unit 2A',
    city: 'Brooklyn',
    state: 'NY',
    zip_code: '11249',
    neighborhood: 'Williamsburg',
    latitude: 40.7195,
    longitude: -73.9566,
    property_type: 'loft',
    floor_number: 2,
    year_built: 1905,
    deposit: 6800,
    fee_type: 'broker_fee',
    image_urls: [],
    available_date: '2026-07-01',
    pet_policy: { cats_allowed: true, dogs_allowed: true, dog_weight_limit_lbs: 80 },
    amenities: ['high ceilings', 'exposed beams', 'dishwasher', 'washer/dryer in unit', 'bike storage'],
    has_doorman: false,
    has_elevator: true,
    has_gym: false,
    has_laundry_in_unit: true,
    has_laundry_in_bldg: false,
    has_dishwasher: true,
    has_ac: true,
    pets_allowed: true,
    has_outdoor_space: true,
    is_active: true,
    scraped_at: '2026-06-14T09:00:00Z',
    last_seen_at: '2026-06-14T09:00:00Z',
    commute: {
      commute_mode: 'transit',
      commute_time_seconds: 2040,
      commute_time_display: '34 min',
      distance_meters: 9600,
      num_transfers: 1,
      route_summary: 'L train to 8 Av, then 1 train to WTC',
      route_steps: [
        {
          step_index: 0,
          mode: 'walking',
          instruction: 'Walk to Bedford Av Station',
          duration_seconds: 240,
          distance_meters: 290,
        },
        {
          step_index: 1,
          mode: 'transit',
          instruction: 'Take the L train toward 8 Av',
          duration_seconds: 1080,
          distance_meters: 7200,
          transit_line: 'L',
          transit_vehicle_type: 'SUBWAY',
          departure_stop: 'Bedford Av',
          arrival_stop: '14 St-Union Sq',
        },
        {
          step_index: 2,
          mode: 'walking',
          instruction: 'Transfer to 4/5/6 or N/R/W',
          duration_seconds: 180,
          distance_meters: 180,
        },
        {
          step_index: 3,
          mode: 'transit',
          instruction: 'Take the 4 train toward Brooklyn Bridge',
          duration_seconds: 420,
          distance_meters: 2100,
          transit_line: '4',
          transit_vehicle_type: 'SUBWAY',
          departure_stop: '14 St-Union Sq',
          arrival_stop: 'Fulton St',
        },
        {
          step_index: 4,
          mode: 'walking',
          instruction: 'Walk to 1 World Trade Center',
          duration_seconds: 120,
          distance_meters: 300,
        },
      ],
      peak_time_used: true,
      departure_time_utc: '2026-06-16T12:30:00Z',
      transit_lines: ['L', '4'],
    },
  },
  {
    id: 'a1b2c3d4-0010-4000-8000-000000000010',
    external_id: 'zillow_1010',
    source: 'zillow',
    listing_url: 'https://zillow.com/homedetails/1010',
    title: '3BR in Riverdale, Bronx',
    description:
      'Rare 3-bedroom in a prewar co-op building with park views. The 1 train provides direct access to Manhattan. Large rooms, great for families.',
    price: 2900,
    price_monthly_cents: 290000,
    bedrooms: 3,
    bathrooms: 2,
    square_feet: 1400,
    address_line1: '5735 Mosholu Ave',
    city: 'Bronx',
    state: 'NY',
    zip_code: '10471',
    neighborhood: 'Riverdale',
    latitude: 40.8831,
    longitude: -73.9117,
    property_type: 'apartment',
    floor_number: 5,
    year_built: 1938,
    deposit: 5800,
    fee_type: 'no_fee',
    image_urls: [],
    available_date: '2026-08-01',
    pet_policy: { cats_allowed: true, dogs_allowed: true, dog_weight_limit_lbs: 25 },
    amenities: ['laundry in building', 'elevator', 'doorman', 'ac', 'park views'],
    has_doorman: true,
    has_elevator: true,
    has_gym: false,
    has_laundry_in_unit: false,
    has_laundry_in_bldg: true,
    has_dishwasher: false,
    has_ac: true,
    pets_allowed: true,
    has_outdoor_space: false,
    is_active: true,
    scraped_at: '2026-06-14T09:00:00Z',
    last_seen_at: '2026-06-14T09:00:00Z',
    commute_pending: true,
  },
];
