import { FoodPost, UserProfile, Notification } from './types';

const now = new Date();
const minutesAgo = (mins: number) => new Date(now.getTime() - mins * 60000);
const minutesFromNow = (mins: number) => new Date(now.getTime() + mins * 60000);

export const SAMPLE_POSTS: FoodPost[] = [
  {
    id: '1',
    title: 'Catered Sushi & Boba',
    eventName: 'Finance Club Speaker Event',
    foodType: 'Sushi & Boba',
    description: 'Tons of excess sushi rolls (salmon, tuna, veggie) and boba drinks from our speaker event. Come grab before we toss!',
    building: 'Tisch Hall',
    room: 'Room LC-25',
    tags: ['Sushi', 'Boba', 'Gluten-Free'],
    quantity: 'plenty',
    postedAt: minutesAgo(3),
    expiresAt: minutesFromNow(45),
    postedBy: 'Sarah K.',
    organization: 'Stern Finance Club',
    pickupInstructions: 'Lower level, room LC-25. Door is open, food is on the table by the entrance.',
    photoUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&h=400&fit=crop',
    claimedCount: 4,
    headingThereCount: 8,
    isGone: false,
    lat: 40.7291,
    lng: -73.9965,
  },
  {
    id: '2',
    title: 'Pizza Party Excess 🍕',
    eventName: 'Marketing Society Mixer',
    foodType: 'Pizza',
    description: '6 boxes of Joes Pizza — cheese, pepperoni, and veggie. Still hot! First come first served.',
    building: 'Kaufman Management Center',
    room: 'Room 2-60',
    tags: ['Pizza', 'Vegetarian'],
    quantity: 'some',
    postedAt: minutesAgo(12),
    expiresAt: minutesFromNow(30),
    postedBy: 'Mike T.',
    organization: 'Marketing Society',
    pickupInstructions: 'Second floor, turn left from the elevator. Pizza is in the kitchen area.',
    photoUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=crop',
    claimedCount: 12,
    headingThereCount: 3,
    isGone: false,
    lat: 40.7287,
    lng: -73.9972,
  },
  {
    id: '3',
    title: 'Mediterranean Platter',
    eventName: 'Consulting Club Case Prep',
    foodType: 'Mediterranean',
    description: 'Hummus, falafel, pita, tabbouleh, and baklava. Plenty left! All from Mamoun\'s.',
    building: 'Paulson Center',
    room: 'Room 310',
    tags: ['Mediterranean', 'Vegetarian', 'Halal', 'Vegan'],
    quantity: 'plenty',
    postedAt: minutesAgo(8),
    expiresAt: minutesFromNow(60),
    postedBy: 'Aisha R.',
    organization: 'Management Consulting Association',
    pickupInstructions: 'Third floor, room 310. Look for the food table near the windows.',
    photoUrl: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&h=400&fit=crop',
    claimedCount: 6,
    headingThereCount: 5,
    isGone: false,
    lat: 40.7295,
    lng: -73.9958,
  },
  {
    id: '4',
    title: 'Bagels & Coffee ☕',
    eventName: 'Morning Recruiting Info Session',
    foodType: 'Bagels & Coffee',
    description: 'Dozen+ bagels with cream cheese, lox spread, and fresh coffee from the Goldman info session.',
    building: 'Tisch Hall',
    room: 'Room UC-24',
    tags: ['Bagels', 'Coffee', 'Breakfast'],
    quantity: 'limited',
    postedAt: minutesAgo(25),
    expiresAt: minutesFromNow(15),
    postedBy: 'James L.',
    organization: 'Career Center',
    pickupInstructions: 'Upper concourse level. Coffee is still warm!',
    photoUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&h=400&fit=crop',
    claimedCount: 18,
    headingThereCount: 2,
    isGone: false,
    lat: 40.7289,
    lng: -73.9967,
  },
  {
    id: '5',
    title: 'Indian Curry Feast 🍛',
    eventName: 'South Asian Business Society',
    foodType: 'Indian',
    description: 'Chicken tikka masala, paneer butter masala, naan, rice, and samosas. Catered by Curry Heights.',
    building: 'Kimmel Center',
    room: 'Room 406',
    tags: ['Indian', 'Halal', 'Vegetarian'],
    quantity: 'some',
    postedAt: minutesAgo(5),
    expiresAt: minutesFromNow(40),
    postedBy: 'Priya M.',
    organization: 'South Asian Business Society',
    pickupInstructions: 'Fourth floor, room 406. Bring your own container if you can!',
    photoUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
    claimedCount: 9,
    headingThereCount: 7,
    isGone: false,
    lat: 40.7297,
    lng: -73.9976,
  },
  {
    id: '6',
    title: 'Cookies & Brownies 🍪',
    eventName: 'Women in Business Panel',
    foodType: 'Dessert',
    description: 'Assorted cookies, brownies, and mini cupcakes from Magnolia Bakery. Perfect study fuel!',
    building: 'Kaufman Management Center',
    room: 'Room 4-80',
    tags: ['Dessert', 'Cookies', 'Snacks'],
    quantity: 'plenty',
    postedAt: minutesAgo(1),
    expiresAt: minutesFromNow(90),
    postedBy: 'Lily W.',
    organization: 'Women in Business',
    pickupInstructions: 'Fourth floor lounge area. Boxes are on the counter.',
    photoUrl: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&h=400&fit=crop',
    claimedCount: 2,
    headingThereCount: 4,
    isGone: false,
    lat: 40.7285,
    lng: -73.9970,
  },
];

export const SAMPLE_USER: UserProfile = {
  id: 'user-1',
  name: 'Prasun Anand',
  email: 'prasun.anand@stern.nyu.edu',
  mealsRescued: 23,
  foodPosted: 8,
  impactPoints: 340,
  badges: [
    { id: 'waste-warrior', name: 'Waste Warrior', icon: '⚔️', description: 'Rescued 10+ meals', earnedAt: new Date('2025-10-15') },
    { id: 'first-bite', name: 'First Bite', icon: '🍕', description: 'Rescued your first meal', earnedAt: new Date('2025-09-01') },
    { id: 'campus-saver', name: 'Campus Saver', icon: '🌱', description: 'Posted food 3+ times', earnedAt: new Date('2025-11-20') },
  ],
  joinedAt: new Date('2025-08-28'),
  favoriteTypes: ['Pizza', 'Sushi', 'Boba'],
};

export const SAMPLE_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    title: '🍣 Free sushi near you!',
    message: 'Catered sushi & boba posted 3 min ago at Tisch Hall',
    type: 'new_food',
    read: false,
    createdAt: minutesAgo(3),
    foodPostId: '1',
  },
  {
    id: 'n2',
    title: '⏰ Hurry! Bagels running low',
    message: 'Bagels at Tisch Hall UC-24 are almost gone',
    type: 'expiring',
    read: false,
    createdAt: minutesAgo(10),
    foodPostId: '4',
  },
  {
    id: 'n3',
    title: '🏆 New badge earned!',
    message: 'You earned the Waste Warrior badge for rescuing 10+ meals',
    type: 'badge',
    read: true,
    createdAt: minutesAgo(120),
  },
  {
    id: 'n4',
    title: '🍕 Pizza alert!',
    message: '6 boxes of pizza at KMC. Go go go!',
    type: 'new_food',
    read: true,
    createdAt: minutesAgo(15),
    foodPostId: '2',
  },
];

export const IMPACT_STATS = {
  totalMealsRescued: 1247,
  totalFoodSaved: '834 lbs',
  activePostsToday: 6,
  activeUsers: 312,
};
